# Generated by Django 4.1 on 2022-09-09 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='percentage',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='bonus',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='money',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
